// @generated by pnpm api:assembly:materialize — do not edit.
//! Generated route crate inventory for the sdkwork-partner assembly.

/// Route crates owned by the sdkwork-partner assembly.
pub const ROUTE_CRATE_PACKAGES: &[&str] = &["sdkwork-routes-partner-backend-api"];
