-- SDKWork partner consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_partner_baseline.sql
-- SDKWork partner consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_partner_baseline.sql
-- folded migration: migrations/postgres/0001_partner_core.up.sql
-- sdkwork:migration
-- id: 0001_partner_core
-- engine: postgres
-- module: sdkwork-partner
-- purpose: partner (multi-level agent) management schema: levels, commission config, partners, customer bindings, join fees, commission events/settlements/distributions, wallets, ledger, withdrawals, stats, audit.
-- reversible: false

-- partner_level: configurable partner levels with commission ratios and join fee.
CREATE TABLE IF NOT EXISTS partner_level (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    level_no INTEGER NOT NULL,
    name VARCHAR(128) NOT NULL,
    customer_revenue_ratio NUMERIC(18,2) NOT NULL DEFAULT 0,
    join_fee_commission_ratio NUMERIC(18,2) NOT NULL DEFAULT 0,
    join_fee NUMERIC(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    sort_order INTEGER NOT NULL DEFAULT 0,
    -- Structured benefit (权益) ladder entries granted by this level:
    -- [{code, name, value, sort}, ...] maintained from the admin UI.
    benefits JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_level_tenant_no ON partner_level (tenant_id, organization_id, level_no);
CREATE INDEX IF NOT EXISTS idx_partner_level_tenant_status ON partner_level (tenant_id, organization_id, status, sort_order, id);

-- partner_commission_config: single-row global commission configuration per tenant.
CREATE TABLE IF NOT EXISTS partner_commission_config (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    revenue_sources TEXT NOT NULL DEFAULT '{"usage_settlement":true,"recharge":true}',
    max_commission_depth BIGINT NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    min_withdrawal_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    -- Platform gross profit margin (percent): customer revenue commissions
    -- are profit-based (base = revenue × margin); join-fee commissions use
    -- the full join fee as their base.
    profit_margin_ratio NUMERIC(18,2) NOT NULL DEFAULT 40.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_commission_config_tenant ON partner_commission_config (tenant_id, organization_id);

-- partner: partner (agent) entities bound to IAM user accounts.
CREATE TABLE IF NOT EXISTS partner_partner (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(256) NOT NULL,
    contact_name VARCHAR(128) NOT NULL DEFAULT '',
    phone VARCHAR(32) NOT NULL DEFAULT '',
    email VARCHAR(256) NOT NULL DEFAULT '',
    level_no INTEGER NOT NULL,
    parent_partner_id BIGINT,
    -- NULL = no bound IAM user account yet; bindable later from the admin list.
    user_account_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    join_fee_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    join_fee_status VARCHAR(16) NOT NULL DEFAULT 'UNPAID',
    joined_at TIMESTAMPTZ,
    owner_id BIGINT NOT NULL DEFAULT 0,
    remark VARCHAR(1024) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_partner_tenant_user ON partner_partner (tenant_id, organization_id, user_account_id);
CREATE INDEX IF NOT EXISTS idx_partner_partner_tenant_parent ON partner_partner (tenant_id, organization_id, parent_partner_id, id);
CREATE INDEX IF NOT EXISTS idx_partner_partner_tenant_status ON partner_partner (tenant_id, organization_id, status, level_no, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_partner_tenant_level ON partner_partner (tenant_id, organization_id, level_no, id);

-- partner_customer_binding: binds a customer (IAM user) to a partner.
CREATE TABLE IF NOT EXISTS partner_customer_binding (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    partner_id BIGINT NOT NULL,
    customer_user_id BIGINT NOT NULL,
    binding_type VARCHAR(16) NOT NULL DEFAULT 'ADMIN_BIND',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    bound_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bound_by BIGINT NOT NULL DEFAULT 0,
    unbound_at TIMESTAMPTZ,
    unbound_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_customer_binding_active
    ON partner_customer_binding (tenant_id, organization_id, customer_user_id) WHERE status = 'ACTIVE';
CREATE INDEX IF NOT EXISTS idx_partner_customer_binding_partner
    ON partner_customer_binding (tenant_id, organization_id, partner_id, status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_customer_binding_customer
    ON partner_customer_binding (tenant_id, organization_id, customer_user_id, id);

-- partner_join_fee_payment: join fee payment records; paying triggers multi-level join-fee commission.
CREATE TABLE IF NOT EXISTS partner_join_fee_payment (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    partner_id BIGINT NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    status VARCHAR(16) NOT NULL DEFAULT 'UNPAID',
    payment_method VARCHAR(32) NOT NULL DEFAULT '',
    paid_at TIMESTAMPTZ,
    paid_by BIGINT,
    remark VARCHAR(1024) NOT NULL DEFAULT '',
    idempotency_key VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_join_fee_payment_idempotency
    ON partner_join_fee_payment (tenant_id, organization_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_partner_join_fee_payment_partner
    ON partner_join_fee_payment (tenant_id, organization_id, partner_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_join_fee_payment_status
    ON partner_join_fee_payment (tenant_id, organization_id, status, created_at, id);

-- partner_commission_event: commissionable revenue events captured from usage settlement / recharge / manual.
CREATE TABLE IF NOT EXISTS partner_commission_event (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    source_type VARCHAR(32) NOT NULL,
    source_ref VARCHAR(128) NOT NULL,
    customer_user_id BIGINT NOT NULL,
    base_amount NUMERIC(18,2) NOT NULL,
    event_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    settled_at TIMESTAMPTZ,
    settled_by BIGINT,
    remark VARCHAR(1024) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_commission_event_source
    ON partner_commission_event (tenant_id, organization_id, source_type, source_ref);
CREATE INDEX IF NOT EXISTS idx_partner_commission_event_status
    ON partner_commission_event (tenant_id, organization_id, status, event_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_commission_event_customer
    ON partner_commission_event (tenant_id, organization_id, customer_user_id, event_at, id);

-- partner_commission_settlement: one settlement batch per commission event.
CREATE TABLE IF NOT EXISTS partner_commission_settlement (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    event_id BIGINT NOT NULL,
    base_amount NUMERIC(18,2) NOT NULL,
    distributed_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    receiver_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'SETTLED',
    computed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    computed_by BIGINT NOT NULL DEFAULT 0,
    remark VARCHAR(1024) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_commission_settlement_event ON partner_commission_settlement (event_id) WHERE event_id > 0;
CREATE INDEX IF NOT EXISTS idx_partner_commission_settlement_tenant ON partner_commission_settlement (tenant_id, organization_id, computed_at, id);

-- partner_commission_distribution: per-receiver commission allocation detail.
CREATE TABLE IF NOT EXISTS partner_commission_distribution (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    settlement_id BIGINT NOT NULL,
    receiver_partner_id BIGINT NOT NULL,
    level_offset INTEGER NOT NULL,
    ratio NUMERIC(18,2) NOT NULL,
    base_amount NUMERIC(18,2) NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    account_ledger_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_commission_distribution_receiver
    ON partner_commission_distribution (settlement_id, receiver_partner_id);
CREATE INDEX IF NOT EXISTS idx_partner_commission_distribution_partner
    ON partner_commission_distribution (tenant_id, organization_id, receiver_partner_id, created_at, id);


-- partner_withdrawal: withdrawal application workflow (apply -> approve/reject -> paid).
CREATE TABLE IF NOT EXISTS partner_withdrawal (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    partner_id BIGINT NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    hold_id BIGINT,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    review_remark VARCHAR(1024) NOT NULL DEFAULT '',
    paid_at TIMESTAMPTZ,
    paid_by BIGINT,
    remark VARCHAR(1024) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_partner_withdrawal_status
    ON partner_withdrawal (tenant_id, organization_id, status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_withdrawal_partner
    ON partner_withdrawal (tenant_id, organization_id, partner_id, created_at, id);

-- partner_stat_snapshot: periodic partner performance snapshots.
CREATE TABLE IF NOT EXISTS partner_stat_snapshot (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    partner_id BIGINT NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    period_type VARCHAR(16) NOT NULL DEFAULT 'MONTH',
    join_fee_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    customer_count INTEGER NOT NULL DEFAULT 0,
    revenue_base NUMERIC(18,2) NOT NULL DEFAULT 0,
    commission_earned NUMERIC(18,2) NOT NULL DEFAULT 0,
    downstream_partner_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_stat_snapshot_period
    ON partner_stat_snapshot (tenant_id, organization_id, partner_id, period_type, period_start);
CREATE INDEX IF NOT EXISTS idx_partner_stat_snapshot_period
    ON partner_stat_snapshot (tenant_id, organization_id, period_type, period_start, id);

-- partner_audit_log: audit trail for partner management writes.
CREATE TABLE IF NOT EXISTS partner_audit_log (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    operator_id BIGINT NOT NULL DEFAULT 0,
    operator_type VARCHAR(16) NOT NULL DEFAULT 'admin',
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64) NOT NULL DEFAULT '',
    target_id BIGINT,
    request_id VARCHAR(128),
    payload TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_partner_audit_log_tenant
    ON partner_audit_log (tenant_id, organization_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_audit_log_target
    ON partner_audit_log (tenant_id, organization_id, target_type, target_id, id);

-- folded migration: migrations/postgres/0001_partner_core.up.sql
-- 0001_partner_core.up.sql
-- sdkwork:migration
-- id: 0001_partner_core
-- engine: postgres
-- module: sdkwork-partner
-- purpose: partner (multi-level agent) management schema.
-- reversible: true
-- rollback: down-migration
-- transactional: true
-- lock: advisory
-- lock_timeout: 15000
-- statement_timeout: 60000



CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_level_tenant_no ON partner_level (tenant_id, organization_id, level_no);
CREATE INDEX IF NOT EXISTS idx_partner_level_tenant_status ON partner_level (tenant_id, organization_id, status, sort_order, id);



CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_commission_config_tenant ON partner_commission_config (tenant_id, organization_id);



CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_partner_tenant_user ON partner_partner (tenant_id, organization_id, user_account_id);
CREATE INDEX IF NOT EXISTS idx_partner_partner_tenant_parent ON partner_partner (tenant_id, organization_id, parent_partner_id, id);
CREATE INDEX IF NOT EXISTS idx_partner_partner_tenant_status ON partner_partner (tenant_id, organization_id, status, level_no, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_partner_tenant_level ON partner_partner (tenant_id, organization_id, level_no, id);



CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_customer_binding_active
    ON partner_customer_binding (tenant_id, organization_id, customer_user_id) WHERE status = 'ACTIVE';
CREATE INDEX IF NOT EXISTS idx_partner_customer_binding_partner
    ON partner_customer_binding (tenant_id, organization_id, partner_id, status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_customer_binding_customer
    ON partner_customer_binding (tenant_id, organization_id, customer_user_id, id);



CREATE INDEX IF NOT EXISTS idx_partner_join_fee_payment_partner
    ON partner_join_fee_payment (tenant_id, organization_id, partner_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_join_fee_payment_status
    ON partner_join_fee_payment (tenant_id, organization_id, status, created_at, id);



CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_commission_event_source
    ON partner_commission_event (tenant_id, organization_id, source_type, source_ref);
CREATE INDEX IF NOT EXISTS idx_partner_commission_event_status
    ON partner_commission_event (tenant_id, organization_id, status, event_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_commission_event_customer
    ON partner_commission_event (tenant_id, organization_id, customer_user_id, event_at, id);



CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_commission_settlement_event ON partner_commission_settlement (event_id) WHERE event_id > 0;
CREATE INDEX IF NOT EXISTS idx_partner_commission_settlement_tenant ON partner_commission_settlement (tenant_id, organization_id, computed_at, id);



CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_commission_distribution_receiver
    ON partner_commission_distribution (settlement_id, receiver_partner_id);
CREATE INDEX IF NOT EXISTS idx_partner_commission_distribution_partner
    ON partner_commission_distribution (tenant_id, organization_id, receiver_partner_id, created_at, id);




CREATE INDEX IF NOT EXISTS idx_partner_withdrawal_status
    ON partner_withdrawal (tenant_id, organization_id, status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_withdrawal_partner
    ON partner_withdrawal (tenant_id, organization_id, partner_id, created_at, id);



CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_stat_snapshot_period
    ON partner_stat_snapshot (tenant_id, organization_id, partner_id, period_type, period_start);
CREATE INDEX IF NOT EXISTS idx_partner_stat_snapshot_period
    ON partner_stat_snapshot (tenant_id, organization_id, period_type, period_start, id);



CREATE INDEX IF NOT EXISTS idx_partner_audit_log_tenant
    ON partner_audit_log (tenant_id, organization_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_audit_log_target
    ON partner_audit_log (tenant_id, organization_id, target_type, target_id, id);

-- folded migration: migrations/postgres/0001_organization_id_not_null.up.sql
-- sdkwork:migration
-- id: 0001_organization_id_not_null
-- engine: postgres
-- module: sdkwork-partner
-- purpose: Enforce organization_id NOT NULL DEFAULT on all tables in the
--   consolidated baseline. NULL rows (pre-standard data anomalies) are
--   backfilled with the platform sentinel before NOT NULL is set, and
--   NOT NULL columns without an explicit default receive the sentinel
--   default, keeping existing deployments consistent with fresh baseline
--   installs.
-- reversible: false
-- rollback: forward-fix (sentinel backfill is the canonical fix; NULL
--   organization rows are data anomalies)
-- transactional: true
-- lock: lightweight
-- lock_timeout: 2s
-- statement_timeout: 30s

BEGIN;

ALTER TABLE partner_level ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_level SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_level ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_level ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_commission_config ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_commission_config SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_commission_config ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_commission_config ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_partner ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_partner SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_partner ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_partner ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_customer_binding ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_customer_binding SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_customer_binding ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_customer_binding ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_join_fee_payment ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_join_fee_payment SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_join_fee_payment ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_join_fee_payment ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_commission_event ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_commission_event SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_commission_event ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_commission_event ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_commission_settlement ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_commission_settlement SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_commission_settlement ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_commission_settlement ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_commission_distribution ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_commission_distribution SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_commission_distribution ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_commission_distribution ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_withdrawal ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_withdrawal SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_withdrawal ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_withdrawal ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_stat_snapshot ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_stat_snapshot SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_stat_snapshot ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_stat_snapshot ALTER COLUMN organization_id SET NOT NULL;

ALTER TABLE partner_audit_log ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 0;
UPDATE partner_audit_log SET organization_id = 0 WHERE organization_id IS NULL;
ALTER TABLE partner_audit_log ALTER COLUMN organization_id SET DEFAULT 0;
ALTER TABLE partner_audit_log ALTER COLUMN organization_id SET NOT NULL;

COMMIT;

-- folded migration: migrations/postgres/0002_partner_user_account_nullable.up.sql
-- sdkwork:migration
-- id: 0002_partner_user_account_nullable
-- engine: postgres
-- module: sdkwork-partner
-- purpose: Allow partners to be created without a bound IAM user account;
--   the account is bindable later from the admin partner list. PostgreSQL
--   unique indexes treat NULLs as distinct, so the existing
--   uk_partner_partner_tenant_user index keeps enforcing one partner per
--   bound account without blocking multiple unbound partners.
-- reversible: false
-- rollback: forward-fix (NULL user_account_id rows are the canonical new state)
-- transactional: true
-- lock: lightweight
-- lock_timeout: 2s
-- statement_timeout: 30s

BEGIN;

ALTER TABLE partner_partner ALTER COLUMN user_account_id DROP NOT NULL;

COMMIT;

-- folded migration: migrations/postgres/0003_join_fee_payment_idempotency_key.up.sql
-- sdkwork:migration
-- id: 0003_join_fee_payment_idempotency_key
-- engine: postgres
-- module: sdkwork-partner
-- purpose: Add a client-generated idempotency key to partner_join_fee_payment
--   so repeated "record join fee payment" submissions (double click, network
--   retry, multi-operator) replay safely instead of creating duplicate
--   payments and duplicate ancestor commission. NULL keys stay allowed for
--   legacy clients and never participate in the unique index.
-- reversible: true
-- rollback: down-migration
-- transactional: true
-- lock: lightweight
-- lock_timeout: 2s
-- statement_timeout: 30s

BEGIN;

ALTER TABLE partner_join_fee_payment ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(128);

CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_join_fee_payment_idempotency
    ON partner_join_fee_payment (tenant_id, organization_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

COMMIT;

-- folded migration: migrations/postgres/0004_partner_level_benefits.up.sql
-- sdkwork:migration
-- id: 0004_partner_level_benefits
-- engine: postgres
-- module: sdkwork-partner
-- purpose: Add the structured benefit (权益) ladder column to partner_level.
--   Each level carries an editable JSONB array [{code, name, value, sort}]
--   describing the commercial entitlements granted to partners of that level
--   (commission pool, training, leads, account manager, regional rights, ...).
--   The default '[]' keeps pre-migration rows readable.
-- reversible: true
-- rollback: ALTER TABLE partner_level DROP COLUMN benefits
-- transactional: true
-- lock: lightweight
-- lock_timeout: 2s
-- statement_timeout: 30s

BEGIN;

ALTER TABLE partner_level
    ADD COLUMN IF NOT EXISTS benefits JSONB NOT NULL DEFAULT '[]'::jsonb;

COMMIT;

-- folded migration: migrations/postgres/0005_partner_commission_config_margin.up.sql
-- sdkwork:migration
-- id: 0005_partner_commission_config_margin
-- engine: postgres
-- module: sdkwork-partner
-- purpose: Add the platform gross profit margin to partner_commission_config.
--   Customer revenue commissions are profit-based: the allocation base equals
--   `revenue × profit_margin_ratio` (default 40.00%), so a 30% commission
--   pool on a 40%-margin business pays at most 12% of revenue. Join-fee
--   commissions keep the full join fee as their base.
-- reversible: true
-- rollback: ALTER TABLE partner_commission_config DROP COLUMN profit_margin_ratio
-- transactional: true
-- lock: lightweight
-- lock_timeout: 2s
-- statement_timeout: 30s

BEGIN;

ALTER TABLE partner_commission_config
    ADD COLUMN IF NOT EXISTS profit_margin_ratio NUMERIC(18,2) NOT NULL DEFAULT 40.00;

COMMIT;

-- folded migration: migrations/postgres/0006_partner_join_apply.up.sql
-- sdkwork:migration
-- id: 0006_partner_join_apply
-- engine: postgres
-- module: sdkwork-partner
-- purpose: Partner join (伙伴计划) schema: partner_application table (apply
--   lifecycle kept independent from the operational partner entity so the
--   partner list, stats, settlement, and tree stay free of application
--   noise) and partner_partner.invite_code (partner-owned invite code for
--   referral growth). One active SUBMITTED application per applicant is
--   enforced by a partial unique index; rejected/cancelled applications
--   remain for audit and allow re-applying.
-- reversible: true
-- rollback: DROP TABLE partner_application; ALTER TABLE partner_partner DROP COLUMN invite_code
-- transactional: true
-- lock: lightweight
-- lock_timeout: 2s
-- statement_timeout: 30s

BEGIN;

CREATE TABLE IF NOT EXISTS partner_application (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    applicant_user_id BIGINT NOT NULL,
    applicant_type VARCHAR(16) NOT NULL DEFAULT 'INDIVIDUAL',
    subject_name VARCHAR(256) NOT NULL DEFAULT '',
    contact_name VARCHAR(128) NOT NULL,
    contact_phone VARCHAR(32) NOT NULL,
    contact_email VARCHAR(256) NOT NULL,
    target_level_no INTEGER NOT NULL DEFAULT 1,
    invite_code VARCHAR(64) NOT NULL DEFAULT '',
    inviter_partner_id BIGINT,
    business_intro VARCHAR(2000) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'SUBMITTED',
    reviewer_user_id BIGINT,
    review_comment VARCHAR(1024) NOT NULL DEFAULT '',
    reviewed_at TIMESTAMPTZ,
    approved_partner_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT
);

-- One active (SUBMITTED) application per applicant; rejected/cancelled
-- records stay for audit and allow re-applying.
CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_application_active_applicant
    ON partner_application (tenant_id, organization_id, applicant_user_id)
    WHERE status = 'SUBMITTED';
CREATE INDEX IF NOT EXISTS idx_partner_application_status
    ON partner_application (tenant_id, organization_id, status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_partner_application_inviter
    ON partner_application (tenant_id, organization_id, inviter_partner_id, id);

-- Partner-owned invite code for referral growth (伙伴计划).
ALTER TABLE partner_partner
    ADD COLUMN IF NOT EXISTS invite_code VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS uk_partner_partner_invite_code
    ON partner_partner (invite_code)
    WHERE invite_code IS NOT NULL AND invite_code <> '';

COMMIT;
